# Docker Compose versiojn
version: "3.9"

# All services defined
services:
  
  app:

    # Composes the Dockerfile in the current directory 
    build: .

    # Uses the image named "customer-feedback-system" and tagged "1.0"
    image: whiskr:1.0

    # The container's name
    container_name: whiskr_app

    # The port the app will be accessible on
    ports:
      - "0724:5000"

    # Mounts the current directory and feedback.json file to the container
    volumes:
      - .:/app
      - ./userdata.json:/app/feedback.json

    # Makes sure the container remains online unless stopped manually
    restart: unless-stopped